name: Best Practice CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  unit_tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: [unit_tests]
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Production
        run: echo "Deploying"
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}